/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * ViteRida Authentication Service API
 *  ViteRidas Authentication servive API endpoints This service generates auth tokens for users and internal services. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@viterida.africa
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "https://authentication.core.viterida.com".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface UserTokenResponse
 */
export interface UserTokenResponse {
    /**
     * User ID
     * @type {string}
     * @memberof UserTokenResponse
     */
    userId: string;
    /**
     * session attached to this token, can be used to invalidate token
     * @type {string}
     * @memberof UserTokenResponse
     */
    sessionId: string;
    /**
     * User JWT token
     * @type {string}
     * @memberof UserTokenResponse
     */
    token: string;
    /**
     * Scopes included in the token
     * @type {Array<string>}
     * @memberof UserTokenResponse
     */
    scopes?: Array<string>;
}


/**
 * UsersApi - fetch parameter creator
 * @export
 */
export const UsersApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Generates a user token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateUserAuthToken(options: any = {}): FetchArgs {
            const localVarPath = `/`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Generates a user token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateUserAuthToken(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<UserTokenResponse> {
            const localVarFetchArgs = UsersApiFetchParamCreator(configuration).generateUserAuthToken(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Generates a user token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateUserAuthToken(options?: any) {
            return UsersApiFp(configuration).generateUserAuthToken(options)(fetch, basePath);
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @summary Generates a user token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public generateUserAuthToken(options?: any) {
        return UsersApiFp(this.configuration).generateUserAuthToken(options)(this.fetch, this.basePath);
    }

}

