// tslint:disable
/**
 * ViteRida Authentication Service API
 *  ViteRidas Authentication servive API endpoints This service generates auth tokens for users and internal services. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@viterida.africa
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
